version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.21.5
    steps:
      - checkout
      - run:
          name: Install Mockery
          command: |
            go install github.com/vektra/mockery/v2@latest
            export PATH=$PATH:$(go env GOPATH)/bin
            mockery --version  # Print mockery version for debugging
            mockery --inpackage --all
      - run:
          name: Set GOPATH/bin in PATH
          command: export PATH=$PATH:$GOPATH/bin
      - run:
          name: Generate Mocks
          command: mockery --inpackage --all
      - run:
          name: Run Unit Tests
          command: |
            go test -v -coverprofile=coverage.out ./...
            go tool cover -html=coverage.out -o coverage.html
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

  codeql-analysis:
    docker:
      - image: golang:1.21.5

    steps:
      - checkout
      - run:
          name: Install CodeQL CLI
          command: |
            wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz -O codeql-bundle-linux64.tar.gz
            tar xzvf codeql-bundle-linux64.tar.gz
            rm codeql-bundle-linux64.tar.gz
            chmod +x codeql
            sudo cp codeql/codeql /usr/local/bin/codeql
            ls -l /usr/local/bin  # Debugging line to check the contents of /usr/local/bin
            echo $PATH           # Debugging line to check the current PATH
            ls -lrt
      - run:
          name: Initialize CodeQL Database
          command: ./codeql/codeql database init paota-codeql-database --language=go --source-root=/home/circleci/project
      - run:
          name: Finalize CodeQL Database
          command: ./codeql/codeql database finalize paota-codeql-database
      - run:
          name: Run CodeQL Analysis
          command: ./codeql/codeql database analyze paota-codeql-database --format=sarif-latest --output=./temp/results-js.sarif

workflows:
  version: 2
  build:
    jobs:
      - build
      - codeql-analysis:
          context: org-global
          requires:
            - build