version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.21.5
    steps:
      - checkout
      - run:
          name: Install Mockery
          command: |
            go install github.com/vektra/mockery/v2@latest
            export PATH=$PATH:$(go env GOPATH)/bin
            mockery --version  # Print mockery version for debugging
            mockery --inpackage --all
      - run:
          name: Set GOPATH/bin in PATH
          command: export PATH=$PATH:$GOPATH/bin
      - run:
          name: Generate Mocks
          command: mockery --inpackage --all
      - run:
          name: Run Unit Tests
          command: |
            go test -v -coverprofile=coverage.out ./...
            go tool cover -html=coverage.out -o coverage.html
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

  codeql-analysis:
    docker:
      - image: cimg/go:1.21.5  # Use an appropriate Go image

    steps:
      - checkout
      - run:
          name: Install CodeQL CLI
          command: |
            curl -L https://github.com/github/codeql-action/releases/latest/download/codeql-runner-linux -o codeql-runner
            chmod +x codeql-runner
            sudo mv codeql-runner /usr/local/bin/codeql
            ls -l /usr/local/bin  # Debugging line to check the contents of /usr/local/bin
            echo $PATH           # Debugging line to check the current PATH
      - run:
          name: Initialize CodeQL Database
          command: codeql database init my-database --language=go
      - run:
          name: Run CodeQL Analysis
          command: codeql database analyze my-database $CIRCLE_WORKING_DIRECTORY/$CIRCLE_PROJECT_REPONAME

workflows:
  version: 2
  build:
    jobs:
      - build
      - codeql-analysis:
          context: org-global
          requires:
            - build