jobs:
  build:
    docker:
      - image: golang:1.21.5
    steps:
      - checkout
      - run:
          name: Install Mockery
          command: |
            curl -LJO https://github.com/vektra/mockery/releases/download/v2.9.0/mockery_2.9.0_Linux_x86_64.tar.gz
            tar -xvf mockery_2.9.0_Linux_x86_64.tar.gz
            mv mockery /usr/local/bin
            mockery --version  # Print mockery version for debugging
            mockery --all --output=mocks
      - run:
          name: Set GOPATH/bin in PATH
          command: export PATH=$PATH:$GOPATH/bin
      - run:
          name: Run Unit Tests
          command: go test -v ./...

version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - build